spring.application.name=backend-spring

spring.datasource.url=jdbc:mysql://localhost:3306/motorepuestos?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Caro121212*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false